### ISSUE TITLE
wouldnt necessarily recommend "HiFi Maximizer"

### ISSUE THREAD

**Issue by adrianmmiller** [JoshuaDoes/pixel-tensor-audio-decompressor#1]
1) ive yet to see any proof of this "jitter" he bangs on about for one - if there is its only demonstratable in a "lab" enviroment and the averge end user would never notice

2) it disables unnnecessary services etc and does too much (even factoring in that i dont beleive it really does anything) - quiote why youre messing with swpapiness., governors, thermals etc, i dont know....this appears more of the usual snakeoil "speed up" or "optimizier" tweak nonsense that been debunked for at least a decade now

Look at the sheer list of batshit craxy stuff he "recommends" you disable...

-----------------

Let you module be what it is, something that *actually does what it sets out to do*....its ALREADY bad enough people load up like 4 audio modules and think it does something (confirmation bias) OR alternately why their sound is shit....whereupon they start filign issues on each of the modules pages looking for the source of their (self inflicted) issue - which i personally have zero time for)

Just my 5 cents as  a module creator.....

**Comment by JoshuaDoes** [comment]
I didn't notice much myself, and I prefer not to use it anyhow because I rely on Wavelet for my EQ needs. However, despite all the attempts at jitter reduction, the main reason I trialed the module and decided to use it as a baseline is because of the fact that it disables the effects framework, which effectively also disables the post-processing from Google's audio tuning configuration (as well as the adjustments made on some other ROMs such as the one I'm using, helluvaOS). My theory is that by disabling the effects framework, he's also effectively disabling Google's frequency cutoffs which are meant to be tailored to these small form factor speakers which would normally prevent them from sounding distorted. When I have Hifi Maximizer disabled, I still prefer my originally recommended volume preset of 865/14, and other users either agree or go with an alternative like 865/13 or 865/12. Perhaps I can add a Go-side hook to the home menu that detects if his effects disabling modules are installed and change the recommendation based on that.
