### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by sanman97** [JoshuaDoes/pixel-tensor-audio-decompressor#2]
Just updated ROM, re-rooted
Uninstalled the module and rebooted and tried a couple times
It shows it still has the buttons menu calibration
So there must be some data remaining

It worked before I guess
I didn't test it out much. My volume level has been stuck maybe by button triggers for media playback. Or is that from this? Couldn't get volume to change without changing to a different screen sometimes.

Hadn't used the speakers much on this phone yet
Pixel 6
So I'd been using this module for a while now and had to reinstall. I wanna test and compare it now.

Do I need the log file?

**Comment by JoshuaDoes** [comment]
First, can you try removing the module, rebooting so Magisk wipes out all the details for it, and then try installing it again? If it fails after this, save the log and post it here so I can gauge what happened. And just in case, make sure to watch this before you try installing it again just in case you're accidentally cancelling the calibration step: https://raw.githubusercontent.com/JoshuaDoes/pixel-tensor-audio-decompressor/dev/media/screen-20230730-191327.mp4

**Comment by JoshuaDoes** [comment]
Module was unmaintained due to life, but it has now been deprecated in favor of an in-app upgraded version! Checkout the README for more details.

Additionally, if you still wish to use this module, a recent pull request was approved that fixes installation for Android 13 through to 15 using the latest version of Magisk. For the time being you will have to manually build this module, but I am considering releasing a final update as a send-off while everyone transitions to my new app, libremedia.
