### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by innit86** [JoshuaDoes/pixel-tensor-audio-decompressor#5]
Hi, does this module also raises volume for bluetooth and wired headphones or just the internal speaker?

Can it be used together with audio misc settings?

https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings

Thanks in advance.

Pixel 7 Pro
Android 14 (Stock)
Build: UP1A.231105.003 (November security patch)

**Comment by HerXayah** [comment]
dito. would be nice to know

**Comment by JoshuaDoes** [comment]
This module is only for the internal phone speakers, sorry! I do plan to make a separate thing for other devices with wrong and unchangeable hardware volumes in Android, and I might even move the logic from this over to there when that happens, but as far as I'm concerned this module can just as easily share the same features so I'd like to do so. For example, the Apple USB-C DAC starts with a hardware volume of 80/120 and can't be changed with the Android user interface, and I find that raising it to 120 the same way I change the values with PTAD will make it sound just as loud as Google's USB-C DAC on Android (but Google's sounds cleaner to me personally lol).

And for that matter, all audio mods work with this as long as they work on your phone speakers. For some reason Wavelet limits your functionality for speakers, but in the past I've managed to trick it into using them with some headset replug bug and the whole range of features work wonderfully when more details can actually make it out. I think the only one you'll have problems with is HiFi Maximizer because it disables all of the speaker protection features as well as the stock audio tunings that Google made, so you'll essentially have a cleaner sound but with none of the factory tunings so all the factory imperfections would shine louder.
